application: pup-dbms-thesis-manager-18
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  
- url: .*
  script: finalproject.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

